// DO NOT EDIT. This code is generated by generate_languages.go 

package alphabet

var languages = LanguageMap{
	"af": Language{ Name:"Afrikaans", Code:"af", Letters:"abcdefghijklmnopqrstuvwxyzáêéèëïíîôóúû"},
	"en": Language{ Name:"English", Code:"en", Letters:"abcdefghijklmnopqrstuvwxyz"},
	"nl": Language{ Name:"Dutch", Code:"nl", Letters:"abcdefghijklmnopqrstuvwxyzàäèéëïĳöü"},
	"da": Language{ Name:"Danish", Code:"da", Letters:"abcdefghijklmnopqrstuvwxyzæøå"},
	"fi": Language{ Name:"Finnish", Code:"fi", Letters:"abcdefghijklmnopqrstuvwxyzäö"},
	"sv": Language{ Name:"Swedish", Code:"sv", Letters:"abcdefghijklmnopqrstuvwxyzåäö"},
	"et": Language{ Name:"Estonian", Code:"et", Letters:"abcdefghijklmnopqrstuvwxyzäöõü"},
	"de": Language{ Name:"German", Code:"de", Letters:"abcdefghijklmnopqrstuvwxyzäöüß"},
	"es": Language{ Name:"Spanish", Code:"es", Letters:"abcdefghijklmnopqrstuvwxyzáéíñóúü"},
	"ar": Language{ Name:"Arabic", Code:"ar", Letters:"أابتثجحخدذرزسشصضطظعغفقكلمنهؤوئىيء"},

}

// Languages returns the map of languages
func Languages() LanguageMap {
	return languages
}
