// Copyright (c) 2024 Andre Jacobs
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

// DO NOT EDIT. This code is generated by generate_languages.go

package alphabet

import (
	"fmt"
)

var languages = LanguageMap{
	"af": Language{Name: "Afrikaans", Code: "af", Letters: "abcdefghijklmnopqrstuvwxyzáêéèëïíîôóúû"},
	"ar": Language{Name: "Arabic", Code: "ar", Letters: "أابتثجحخدذرزسشصضطظعغفقكلمنهؤوئىيء"},
	"da": Language{Name: "Danish", Code: "da", Letters: "abcdefghijklmnopqrstuvwxyzæøå"},
	"de": Language{Name: "German", Code: "de", Letters: "abcdefghijklmnopqrstuvwxyzäöüß"},
	"en": Language{Name: "English", Code: "en", Letters: "abcdefghijklmnopqrstuvwxyz"},
	"es": Language{Name: "Spanish", Code: "es", Letters: "abcdefghijklmnopqrstuvwxyzáéíñóúü"},
	"et": Language{Name: "Estonian", Code: "et", Letters: "abcdefghijklmnopqrstuvwxyzäöõü"},
	"fi": Language{Name: "Finnish", Code: "fi", Letters: "abcdefghijklmnopqrstuvwxyzäö"},
	"fr": Language{Name: "French", Code: "fr", Letters: "abcdefghijklmnopqrstuvwxyzàâæçéèêëîïôœùûüÿ"},
	"nl": Language{Name: "Dutch", Code: "nl", Letters: "abcdefghijklmnopqrstuvwxyzàäèéëïĳöü"},
	"sv": Language{Name: "Swedish", Code: "sv", Letters: "abcdefghijklmnopqrstuvwxyzåäö"},
}

// Builtin returns the built-in language for the given ISO 639 set 1 language.
func Builtin(code LanguageCode) (Language, error) {
	lang, exists := languages[code]
	if !exists {
		return Language{}, fmt.Errorf("no built-in language found with code %q", code)
	}
	return lang, nil
}

// MustBuiltin returns the built-in language for the given ISO 639 set 1 language or panics.
func MustBuiltin(code LanguageCode) Language {
	lang, exists := languages[code]
	if !exists {
		panic(fmt.Errorf("no built-in language found with code %q", code))
	}
	return lang
}

// BuiltinLanguages return the built-in languages.
func BuiltinLanguages() LanguageMap {
	return languages
}
